/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.thuchanh3;

import java.net.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class BaiThucHanh1 extends javax.swing.JFrame {

    /**
     * Creates new form BaiThucHanh1
     */
    public BaiThucHanh1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog_CheckIP = new javax.swing.JDialog();
        JLabel_CheckIP = new javax.swing.JLabel();
        jTextField_CheckIP = new javax.swing.JTextField();
        jButton_checkIP = new javax.swing.JButton();
        jButton_exit = new javax.swing.JButton();
        jMenuBar_BaiThucHanh1 = new javax.swing.JMenuBar();
        jMenu_system = new javax.swing.JMenu();
        jMenu_functions = new javax.swing.JMenu();
        jMenuItem_checkIP = new javax.swing.JMenuItem();
        jMenuItem_findDomainByIP = new javax.swing.JMenuItem();
        jMenuItem_find_IP_byDomain = new javax.swing.JMenuItem();
        jMenuItem_findLocalIP = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        jDialog_CheckIP.setTitle("Chương trình kiểm tra IP");
        jDialog_CheckIP.setSize(new java.awt.Dimension(708, 160));

        JLabel_CheckIP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLabel_CheckIP.setText("Nhập địa chỉ IP cần kiểm tra");

        jTextField_CheckIP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jButton_checkIP.setBackground(java.awt.SystemColor.activeCaption);
        jButton_checkIP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_checkIP.setText("Kiểm tra");
        jButton_checkIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_checkIPActionPerformed(evt);
            }
        });

        jButton_exit.setBackground(java.awt.SystemColor.activeCaption);
        jButton_exit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_exit.setText("Thoát");
        jButton_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog_CheckIPLayout = new javax.swing.GroupLayout(jDialog_CheckIP.getContentPane());
        jDialog_CheckIP.getContentPane().setLayout(jDialog_CheckIPLayout);
        jDialog_CheckIPLayout.setHorizontalGroup(
            jDialog_CheckIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_CheckIPLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(JLabel_CheckIP)
                .addGap(18, 18, 18)
                .addComponent(jTextField_CheckIP)
                .addContainerGap())
            .addGroup(jDialog_CheckIPLayout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jButton_checkIP)
                .addGap(182, 182, 182)
                .addComponent(jButton_exit)
                .addContainerGap(173, Short.MAX_VALUE))
        );
        jDialog_CheckIPLayout.setVerticalGroup(
            jDialog_CheckIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_CheckIPLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jDialog_CheckIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel_CheckIP)
                    .addComponent(jTextField_CheckIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog_CheckIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_checkIP)
                    .addComponent(jButton_exit))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thực hành lập trình mạng");

        jMenu_system.setText("Hệ Thống");
        jMenuBar_BaiThucHanh1.add(jMenu_system);

        jMenu_functions.setText("Chức Năng");

        jMenuItem_checkIP.setText("kiểm tra IP");
        jMenuItem_checkIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_checkIPActionPerformed(evt);
            }
        });
        jMenu_functions.add(jMenuItem_checkIP);

        jMenuItem_findDomainByIP.setText("Tìm IP của tên miền");
        jMenu_functions.add(jMenuItem_findDomainByIP);

        jMenuItem_find_IP_byDomain.setText("Tìm tên miền của IP");
        jMenu_functions.add(jMenuItem_find_IP_byDomain);

        jMenuItem_findLocalIP.setText("Tìm IP của máy cục bộ");
        jMenu_functions.add(jMenuItem_findLocalIP);

        jMenuItem5.setText("Kiểm tra IP");
        jMenu_functions.add(jMenuItem5);

        jMenuItem6.setText("Kiểm tra 2 tên miền");
        jMenu_functions.add(jMenuItem6);

        jMenuBar_BaiThucHanh1.add(jMenu_functions);

        setJMenuBar(jMenuBar_BaiThucHanh1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_checkIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_checkIPActionPerformed
        this.setVisible(false);
        jDialog_CheckIP.setVisible(true);
        jDialog_CheckIP.setLocationRelativeTo(this);
    }//GEN-LAST:event_jMenuItem_checkIPActionPerformed

    //Sự kiện kiểm tra IP
    private void jButton_checkIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_checkIPActionPerformed
        String IP = jTextField_CheckIP.getText();
        try {
            InetAddress host = Inet4Address.getByName(IP);
            if(host != null) {
                if (IP.contains(".")) {
                    JOptionPane.showMessageDialog(null, "Đây là IPV4");
                } else {
                    JOptionPane.showMessageDialog(null, "Đây là IPV6");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Địa chỉ IP của bạn nhập sai!!!");
            }
        } catch(Exception ex) {
            JOptionPane.showMessageDialog(null, "Địa chỉ IP của bạn nhập sai!!!:\n" +ex.toString());
        }
    }//GEN-LAST:event_jButton_checkIPActionPerformed

    private void jButton_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_exitActionPerformed
        jDialog_CheckIP.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jButton_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaiThucHanh1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaiThucHanh1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaiThucHanh1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaiThucHanh1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaiThucHanh1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel_CheckIP;
    private javax.swing.JButton jButton_checkIP;
    private javax.swing.JButton jButton_exit;
    private javax.swing.JDialog jDialog_CheckIP;
    private javax.swing.JMenuBar jMenuBar_BaiThucHanh1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem_checkIP;
    private javax.swing.JMenuItem jMenuItem_findDomainByIP;
    private javax.swing.JMenuItem jMenuItem_findLocalIP;
    private javax.swing.JMenuItem jMenuItem_find_IP_byDomain;
    private javax.swing.JMenu jMenu_functions;
    private javax.swing.JMenu jMenu_system;
    private javax.swing.JTextField jTextField_CheckIP;
    // End of variables declaration//GEN-END:variables
}
