/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.thuchanh2_3;

import java.awt.GridLayout;
import java.io.File;
import java.io.FileWriter;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author Admin
 */
public class listPrimeNumber extends javax.swing.JFrame {

    /**
     * Creates new form listNumberAndPrime
     */
    public listPrimeNumber() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStartNumber = new javax.swing.JLabel();
        lbl_LastNumber = new javax.swing.JLabel();
        lblFileName = new javax.swing.JLabel();
        btnList = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnSavePrimeNumber = new javax.swing.JButton();
        txtStartNumber = new javax.swing.JTextField();
        txtLastNumber = new javax.swing.JTextField();
        txtFileName = new javax.swing.JTextField();
        JScrollPane = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblStartNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblStartNumber.setText("Số bắt đầu");

        lbl_LastNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_LastNumber.setText("Số kết thúc");

        lblFileName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFileName.setText("Tên tập tin");

        btnList.setBackground(java.awt.SystemColor.activeCaption);
        btnList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnList.setText("List");
        btnList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListActionPerformed(evt);
            }
        });

        btnReset.setBackground(java.awt.SystemColor.activeCaption);
        btnReset.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnSavePrimeNumber.setBackground(java.awt.SystemColor.activeCaption);
        btnSavePrimeNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSavePrimeNumber.setText("Lưu số nguyên tố");
        btnSavePrimeNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePrimeNumberActionPerformed(evt);
            }
        });

        txtStartNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtLastNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtFileName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextArea.setColumns(20);
        jTextArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea.setRows(5);
        JScrollPane.setViewportView(jTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JScrollPane)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblStartNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtStartNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                                .addComponent(txtFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_LastNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtLastNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSavePrimeNumber)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnList)
                                .addComponent(btnReset)))))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStartNumber)
                    .addComponent(btnList)
                    .addComponent(txtStartNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_LastNumber)
                    .addComponent(btnReset)
                    .addComponent(txtLastNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFileName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSavePrimeNumber)
                        .addComponent(txtFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //hàm kiểm tra số nguyên tố
    static boolean isPrime(int n) {
        // Corner case
        if (n <= 1) {
            return false;
        }
        // Check from 2 to n-1
        for (int i = 2; i < n; i++) {
            if (n % i == 0) {
                return false;
            }
        }
        return true;
    }

    private void btnSavePrimeNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePrimeNumberActionPerformed
        int startNumber = Integer.parseInt(txtStartNumber.getText());
        int lastNumber = Integer.parseInt(txtLastNumber.getText());

        try {
            FileWriter fw = new FileWriter(new File(txtFileName.getText()));
            int count = 0;
            String title = "Số kí tự từ " + startNumber + " đến " + lastNumber + ":\n";
            for (int i = startNumber; i <= lastNumber; i++) {
                if (isPrime(i)) {
                    String primeNumber = String.valueOf(i) + "     ";
                    count++;
                    if(count == 5){
                        primeNumber += "\n";
                        count = 0;
                    }
                    title += primeNumber;
                }
            }
            fw.write(title);
            fw.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnSavePrimeNumberActionPerformed

    //Hiển thị ra danh sách từ số bắt đầu đến số kết thúc do người dùng nhập vào
    private void btnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListActionPerformed

        int startNumber = Integer.parseInt(txtStartNumber.getText());
        int lastNumber = Integer.parseInt(txtLastNumber.getText());
        
        jTextArea.append("Số kí tự từ " + startNumber + " đến " + lastNumber + ":\n");
//        for (int i = startNumber; i <= lastNumber; i++) {
//            jTextArea.append(String.valueOf(i) + " ");
//        }
        int count = 0;
        for(int i = startNumber; i <= lastNumber; i++){
            jTextArea.append(String.valueOf(i) + "     ");
            count++;    
            if(count == 5){
                jTextArea.append("\n");
                count = 0;
            }
        }
    }//GEN-LAST:event_btnListActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        jTextArea.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listPrimeNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listPrimeNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listPrimeNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listPrimeNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listPrimeNumber().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPane;
    private javax.swing.JButton btnList;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSavePrimeNumber;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JLabel lblFileName;
    private javax.swing.JLabel lblStartNumber;
    private javax.swing.JLabel lbl_LastNumber;
    private javax.swing.JTextField txtFileName;
    private javax.swing.JTextField txtLastNumber;
    private javax.swing.JTextField txtStartNumber;
    // End of variables declaration//GEN-END:variables
}
